import { spawn } from "node:child_process";
import { fileURLToPath } from "node:url";

import { loadYoutubeSettings } from "../packages/youtube-cli/src/config";

interface CliEnvelope<T = unknown> {
  ok: boolean;
  data?: T;
  error?: {
    code: string;
    message: string;
    details?: unknown;
  };
}

interface SmokeCheck {
  name: string;
  state: "passed" | "failed" | "skipped";
  command?: string[];
  detail?: unknown;
}

const repoRoot = fileURLToPath(new URL("..", import.meta.url));
const checks: SmokeCheck[] = [];
const profile = resolveProfile();
const youtubeSettings = loadYoutubeSettings(repoRoot);
const expectedChannelId = envString("YT_CLI_EXPECTED_CHANNEL_ID") ?? youtubeSettings.expectedChannelId;
const expectedChannelTitle = envString("YT_CLI_EXPECTED_CHANNEL_TITLE") ?? youtubeSettings.expectedChannelTitle;

if (process.env.YT_CLI_LIVE !== "1") {
  finish(2, {
    ok: false,
    error: {
      code: "yt_cli_live_disabled",
      message: "Set YT_CLI_LIVE=1 to run live YouTube smoke checks."
    },
    checks
  });
}

const authStatus = await runStep("auth status", ["auth", "status", "--profile", profile, "--json"]);
if (authStatus.exitCode !== 0 || !authStatus.envelope.ok) {
  finish(2, {
    ok: false,
    error: authStatus.envelope.error ?? { code: "yt_cli_auth_status_failed", message: "auth status failed" },
    checks
  });
}

const authData = authStatus.envelope.data as { authenticated?: boolean; state?: string } | undefined;
if (!authData?.authenticated) {
  if (process.env.YT_CLI_AUTH === "1") {
    const authArgs = ["auth", "start", "--profile", profile, "--force-consent", "--json"];
    if (process.env.YT_CLI_AUTH_SCOPE) authArgs.splice(4, 0, "--scope", process.env.YT_CLI_AUTH_SCOPE);
    const authStart = await runStep("auth start", authArgs);
    if (authStart.exitCode !== 0 || !authStart.envelope.ok) {
      finish(2, {
        ok: false,
        error: authStart.envelope.error ?? { code: "yt_cli_auth_start_failed", message: "auth start failed" },
        checks
      });
    }
  } else {
    checks.push({
      name: "auth guidance",
      state: "skipped",
      detail: `Run: YT_CLI_LIVE=1 YT_CLI_PROFILE=${profile} YT_CLI_AUTH=1 bun run yt-cli:live-smoke`
    });
    finish(2, {
      ok: false,
      error: {
        code: "yt_cli_auth_missing",
        message: `No authenticated YouTube token for profile ${profile}.`
      },
      checks
    });
  }
}

const channelEnvelope = await requireStep("channel mine", ["channel", "mine", "--profile", profile, "--json"]);
assertExpectedChannel(extractChannel(channelEnvelope.data));
await requireStep("videos list", ["videos", "list", "--profile", profile, "--max-results", "5", "--json"]);
await requireStep("upload status", ["upload", "status", "--profile", profile, "--json"]);

if (process.env.YT_CLI_COMMENT_ID) {
  await requireStep("comments reply dry-run", [
    "comments",
    "reply",
    "--profile",
    profile,
    "--parent-id",
    process.env.YT_CLI_COMMENT_ID,
    "--text",
    process.env.YT_CLI_COMMENT_TEXT ?? "Live smoke dry-run reply from yt-cli.",
    "--dry-run",
    "--json"
  ]);
} else {
  checks.push({ name: "comments reply dry-run", state: "skipped", detail: "Set YT_CLI_COMMENT_ID to include a comment dry-run." });
}

if (process.env.YT_CLI_LIVE_UPLOAD === "1") {
  if (!process.env.YT_CLI_UPLOAD_FILE) {
    finish(2, {
      ok: false,
      error: {
        code: "yt_cli_upload_file_missing",
        message: "Set YT_CLI_UPLOAD_FILE before YT_CLI_LIVE_UPLOAD=1."
      },
      checks
    });
  }
  await requireStep("upload create private", [
    "upload",
    "create",
    "--profile",
    profile,
    "--file",
    process.env.YT_CLI_UPLOAD_FILE,
    "--title",
    process.env.YT_CLI_UPLOAD_TITLE ?? "yt-cli live smoke private upload",
    "--description",
    process.env.YT_CLI_UPLOAD_DESCRIPTION ?? "Private live smoke upload generated by yt-cli.",
    "--privacy",
    "private",
    "--made-for-kids",
    process.env.YT_CLI_UPLOAD_MADE_FOR_KIDS ?? "false",
    "--contains-synthetic-media",
    process.env.YT_CLI_UPLOAD_SYNTHETIC ?? "true",
    "--json"
  ]);
} else {
  checks.push({ name: "upload create private", state: "skipped", detail: "Set YT_CLI_LIVE_UPLOAD=1 and YT_CLI_UPLOAD_FILE to include a private upload." });
}

finish(0, { ok: true, profile, checks });

function resolveProfile(): string {
  const profile = envString("YT_CLI_PROFILE") ?? envString("YOUTUBE_PROFILE");
  if (!profile) {
    finish(2, {
      ok: false,
      error: {
        code: "yt_cli_profile_required",
        message: "Set YT_CLI_PROFILE to the user/workspace profile that owns this authorization."
      },
      checks
    });
  }
  return profile;
}

function envString(key: string): string | undefined {
  const value = process.env[key]?.trim();
  return value || undefined;
}

function extractChannel(data: unknown): { id?: string; title?: string } {
  const record = data && typeof data === "object" && !Array.isArray(data) ? (data as Record<string, unknown>) : undefined;
  const channel = record?.channel && typeof record.channel === "object" && !Array.isArray(record.channel)
    ? (record.channel as Record<string, unknown>)
    : undefined;
  return {
    id: typeof channel?.id === "string" ? channel.id : undefined,
    title: typeof channel?.title === "string" ? channel.title : undefined
  };
}

function assertExpectedChannel(channel: { id?: string; title?: string }): void {
  if (!expectedChannelId && !expectedChannelTitle) {
    const detail = "Set YT_CLI_EXPECTED_CHANNEL_ID or youtube.expectedChannelId before live smoke can continue.";
    if (process.env.YT_CLI_ALLOW_UNBOUND_CHANNEL === "1") {
      checks.push({ name: "expected channel", state: "skipped", detail });
      return;
    }
    checks.push({ name: "expected channel", state: "failed", detail });
    finish(2, {
      ok: false,
      error: {
        code: "yt_cli_expected_channel_missing",
        message: detail
      },
      checks
    });
  }

  const mismatches: Record<string, { expected: string; actual?: string }> = {};
  if (expectedChannelId && channel.id !== expectedChannelId) {
    mismatches.id = { expected: expectedChannelId, actual: channel.id };
  }
  if (expectedChannelTitle && channel.title !== expectedChannelTitle) {
    mismatches.title = { expected: expectedChannelTitle, actual: channel.title };
  }
  if (Object.keys(mismatches).length > 0) {
    checks.push({ name: "expected channel", state: "failed", detail: mismatches });
    finish(2, {
      ok: false,
      error: {
        code: "yt_cli_expected_channel_mismatch",
        message: "Authenticated YouTube channel does not match the expected user/workspace channel.",
        details: mismatches
      },
      checks
    });
  }

  checks.push({
    name: "expected channel",
    state: "passed",
    detail: {
      ...(channel.id ? { id: channel.id } : {}),
      ...(channel.title ? { title: channel.title } : {})
    }
  });
}

async function requireStep(name: string, args: string[]): Promise<CliEnvelope> {
  const result = await runStep(name, args);
  if (result.exitCode !== 0 || !result.envelope.ok) {
    finish(1, {
      ok: false,
      error: result.envelope.error ?? { code: "yt_cli_live_step_failed", message: `${name} failed` },
      checks
    });
  }
  return result.envelope;
}

async function runStep(name: string, args: string[]): Promise<{ exitCode: number | null; envelope: CliEnvelope }> {
  const command = [process.execPath, "--silent", "packages/youtube-cli/src/cli.ts", ...args];
  const result = await run(command);
  let envelope: CliEnvelope;
  try {
    envelope = JSON.parse(result.stdout) as CliEnvelope;
  } catch {
    envelope = {
      ok: false,
      error: {
        code: "yt_cli_json_invalid",
        message: `Could not parse JSON output for ${name}.`
      }
    };
  }
  checks.push({
    name,
    state: result.exitCode === 0 && envelope.ok ? "passed" : "failed",
    command: redactCommand(command),
    detail: envelope.ok ? summarizeData(envelope.data) : envelope.error
  });
  return { exitCode: result.exitCode, envelope };
}

function run(command: string[]): Promise<{ exitCode: number | null; stdout: string; stderr: string }> {
  return new Promise((resolve, reject) => {
    const child = spawn(command[0], command.slice(1), {
      cwd: repoRoot,
      env: process.env,
      stdio: ["ignore", "pipe", "pipe"]
    });
    let stdout = "";
    let stderr = "";
    child.stdout.on("data", (chunk) => {
      stdout += String(chunk);
    });
    child.stderr.on("data", (chunk) => {
      stderr += String(chunk);
    });
    child.on("error", reject);
    child.on("close", (exitCode) => resolve({ exitCode, stdout: redact(stdout), stderr: redact(stderr) }));
  });
}

function summarizeData(data: unknown): unknown {
  if (!data || typeof data !== "object") return data;
  const record = data as Record<string, unknown>;
  if (Array.isArray(record.videos)) return { videos: record.videos.length };
  if (Array.isArray(record.uploads)) return { uploads: record.uploads.length };
  if (record.channel && typeof record.channel === "object") {
    const channel = record.channel as Record<string, unknown>;
    return { channel: { id: channel.id, title: channel.title } };
  }
  if (record.comment && typeof record.comment === "object") {
    const comment = record.comment as Record<string, unknown>;
    return { comment: { action: comment.action, dryRun: comment.dryRun } };
  }
  return record;
}

function redactCommand(command: string[]): string[] {
  return command.map((part) => (part.includes("secret") || part.includes("token") ? "[REDACTED]" : part));
}

function redact(value: string): string {
  return value
    .replace(/("?(?:accessToken|refreshToken|access_token|refresh_token|clientSecret|client_secret)"?\s*[:=]\s*)("[^"]+"|[^\s,}]+)/gi, "$1[REDACTED]")
    .replace(/(Authorization:\s*Bearer\s+)[^\s]+/gi, "$1[REDACTED]");
}

function finish(exitCode: number, payload: Record<string, unknown>): never {
  process.stdout.write(`${JSON.stringify(payload, null, 2)}\n`);
  process.exit(exitCode);
}
